// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buteohtchnbywfkjwjhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1dGVvaHRjaG5ieXdma2p3amhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MTI2NjIsImV4cCI6MjA2NDI4ODY2Mn0.XSPgy_IVTNf5PGhwKeq94Q9OCImqkcBsuIBJlZjp7_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);